Repository CHEERUP-LEGO/Backend, pull requests merged in 2025-03, with the labels that each got.

#2 [Feat #1] 데이터베이스 분리 & 로깅 kafka 비동기화 (#1)
  jobbotdari/build.gradle
  jobbotdari/src/main/java/com/team9/jobbotdari/aspect/LoggingAspect.java
  jobbotdari/src/main/java/com/team9/jobbotdari/entity/Log.java
  jobbotdari/src/main/java/com/team9/jobbotdari/kafka/dto/LogMessage.java
  jobbotdari/src/main/java/com/team9/jobbotdari/kafka/messagequeue/KafkaLogProducer.java
  jobbotdari/src/main/java/com/team9/jobbotdari/kafka/messagequeue/KafkaProducerConfig.java
  jobbotdari/src/main/java/com/team9/jobbotdari/repository/LogRepository.java
  jobbotdari_user/build.gradle
  jobbotdari_user/src/main/java/com/team9/jobbotdari/kafka/dto/LogMessage.java
  jobbotdari_user/src/main/java/com/team9/jobbotdari/kafka/messagequeue/KafkaConsumerConfig.java
  jobbotdari_user/src/main/java/com/team9/jobbotdari/kafka/messagequeue/KafkaLogConsumer.java
Labels: enhancement

#9 [Feat #5] API Gateway 로드밸런싱 구현 (#5)
  gatewayserver/src/main/resources/application.yml
Labels: enhancement

#11 [FIX #6] 데이터베이스 rds 전환 & admin 유저 삭제 에러 수정
  docker-compose-outer.yml
  jobbotdari/Dockerfile
  jobbotdari/src/main/java/com/team9/jobbotdari/config/AppInitializer.java
  jobbotdari/src/main/java/com/team9/jobbotdari/entity/Company.java
  jobbotdari/src/main/resources/application.yml
  jobbotdari_user/Dockerfile
  jobbotdari_user/src/main/java/com/team9/jobbotdari/entity/User.java
Labels: bug, enhancement

#13 [FIX #7] Cloud Gateway 에러 수정 (#12)
  gatewayserver/src/main/resources/application.yml
Labels: bug
